# Generated by Django 4.1.4 on 2022-12-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_province_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='sin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
